"""Literal v1 data used exclusively by explicit migration tests."""

VALID_ALL_VARIANTS = {'schema_version': 1,
 'id': 'all-variants',
 'title': 'All manifest variants',
 'description': 'A literal fixture covering every surface and completion form.',
 'entry_module_id': 'module-one',
 'policies': {'content_sharing': 'explicit_only',
              'durable_mutation': 'proposal_or_direct_student_action',
              'terminal_execution': 'student_only',
              'conversation_memory': 'session_only',
              'max_shared_chars': 8192,
              'workspace_write_globs': ['work/*.py', 'notes/*.md']},
 'modules': [{'id': 'module-one',
              'title': 'Module One',
              'description': '',
              'phases': [{'id': 'read-html',
                          'title': 'Read HTML',
                          'kind': 'read',
                          'teacher_mode': 'reading_companion',
                          'surfaces': [{'id': 'lesson-html',
                                        'type': 'html',
                                        'role': 'primary',
                                        'path': 'lesson.html'},
                                       {'id': 'lesson-markdown',
                                        'type': 'markdown',
                                        'role': 'reference',
                                        'path': 'lesson.md'},
                                       {'id': 'lesson-source',
                                        'type': 'source',
                                        'role': 'evidence',
                                        'path': 'src/example.py'}],
                          'completion': {'type': 'manual'},
                          'capabilities': {'chat': True,
                                           'hint_level': 'graduated',
                                           'share_selection': True,
                                           'share_cell': True,
                                           'share_output': False,
                                           'create_profile_proposal': False,
                                           'create_course_proposal': False,
                                           'create_workspace_proposal': True}},
                         {'id': 'predict-notebook',
                          'title': 'Predict in notebook',
                          'kind': 'predict',
                          'teacher_mode': 'socratic_guide',
                          'surfaces': [{'id': 'exercise-notebook',
                                        'type': 'notebook',
                                        'role': 'exercise',
                                        'path': 'notebooks/exercise.ipynb',
                                        'match': {'cell_ids': ['cell-real-uuid'],
                                                  'cell_tags': ['prediction']}}],
                          'completion': {'type': 'prediction_recorded',
                                         'record_id': 'prediction-one'},
                          'capabilities': {'chat': True,
                                           'hint_level': 'graduated',
                                           'share_selection': True,
                                           'share_cell': True,
                                           'share_output': False,
                                           'create_profile_proposal': False,
                                           'create_course_proposal': False,
                                           'create_workspace_proposal': True}},
                         {'id': 'watch-local',
                          'title': 'Watch local segment',
                          'kind': 'watch',
                          'teacher_mode': 'orienter',
                          'surfaces': [{'id': 'local-video',
                                        'type': 'video',
                                        'role': 'primary',
                                        'path': 'media/lesson.mp4',
                                        'start_seconds': 2.5,
                                        'end_seconds': 8.0}],
                          'completion': {'type': 'receipt_recorded', 'record_id': 'video-receipt'},
                          'capabilities': {'chat': True,
                                           'hint_level': 'graduated',
                                           'share_selection': True,
                                           'share_cell': True,
                                           'share_output': False,
                                           'create_profile_proposal': False,
                                           'create_course_proposal': False,
                                           'create_workspace_proposal': True}},
                         {'id': 'watch-remote',
                          'title': 'Watch remote segment',
                          'kind': 'watch',
                          'teacher_mode': 'orienter',
                          'surfaces': [{'id': 'remote-video',
                                        'type': 'video',
                                        'role': 'reference',
                                        'url': 'https://cdn.example.test/lesson.mp4',
                                        'start_seconds': 0,
                                        'end_seconds': 12}],
                          'completion': {'type': 'manual'},
                          'capabilities': {'chat': True,
                                           'hint_level': 'graduated',
                                           'share_selection': True,
                                           'share_cell': True,
                                           'share_output': False,
                                           'create_profile_proposal': False,
                                           'create_course_proposal': False,
                                           'create_workspace_proposal': True}},
                         {'id': 'lab-terminal',
                          'title': 'Run the lab',
                          'kind': 'lab',
                          'teacher_mode': 'debugging_coach',
                          'surfaces': [{'id': 'lab-terminal',
                                        'type': 'terminal',
                                        'role': 'exercise',
                                        'label': 'Run tests',
                                        'argv': ['uv', 'run', 'pytest', '-q'],
                                        'cwd': '.'},
                                       {'id': 'reference-link',
                                        'type': 'external',
                                        'role': 'reference',
                                        'url': 'https://docs.example.test/course'}],
                          'completion': {'type': 'artifact_exists',
                                         'record_id': 'lab-artifact',
                                         'path': 'work/result.json'},
                          'capabilities': {'chat': True,
                                           'hint_level': 'graduated',
                                           'share_selection': True,
                                           'share_cell': True,
                                           'share_output': False,
                                           'create_profile_proposal': False,
                                           'create_course_proposal': False,
                                           'create_workspace_proposal': True}}]}]}
